fix function judgment_parameters
v2fly/fhs-install-v2ray pull request #104
Opened 2020-09-17 10:37 UTC by xiagw

2020-09-17 14:41 UTC, IceCodeNew commented on install-release.sh
> +            if echo "${2:?undefine var}" | grep -qEo '^(http|https|socks4|socks4a|socks5|socks5h)://'; then
其实我觉得我们甚至不一定非要在脚本里做这么细致的代理 URL 匹配。
只要原样把参数传递给 `curl` 就好了，这样出现问题的时候用户看到的应该是 `curl` 返回的错误信息，比我们自己自定义一个错误信息会更容易拿去搜索引擎搜寻。

2020-09-17 14:42 UTC, IceCodeNew commented on install-release.sh
> +    echo '  --specific       Install the specified version of V2Ray, e.g., --specific v4.18.0'
没有一个足够强的理由，就不要引入这种函数签名变化。

2020-09-17 14:44 UTC, IceCodeNew requested changes
见上面的讨论。

2020-09-18 05:04 UTC, xiagw commented
> 没有一个足够强的理由，就不要引入这种函数签名变化。 

--version 一般几乎所有命令都是指查询版本好，
你放在这里 不伦不类。产生歧义

2020-09-18 05:24 UTC, IceCodeNew commented
> > 没有一个足够强的理由，就不要引入这种函数签名变化。
> 
> --version 一般几乎所有命令都是指查询版本号，
> 你放在这里 不伦不类。产生歧义

这代码又不是我写的……
我不喜欢你的批评方式。

最后说回话题，你的主张是有一定道理的。但是我不接受它的原因是我无法估计这个改变会让多少人受到影响。
最近 v2ray-core 才正式化了 VmessAEAD，期间引入了很多不向前兼容的变化。所以我想可能是会有客户在升级/重装 v2ray 的时候固定在某一个版本上的。而你这样改动的 ROI 在我看来并不值得。

2020-09-18 05:26 UTC, xiagw commented on install-release.sh
> +            if echo "${2:?undefine var}" | grep -qEo '^(http|https|socks4|socks4a|socks5|socks5h)://'; then
随便你，
我只是在你的基础上修改而已，

2020-09-18 05:26 UTC, xiagw commented on install-release.sh
> +    echo '  --specific       Install the specified version of V2Ray, e.g., --specific v4.18.0'
--version 一般几乎所有命令都是指查询版本号，
你放在这里 不伦不类。产生歧义

2020-09-18 05:33 UTC, IceCodeNew commented
你可能还记得我之前在其他 PR 和你说我们写这个脚本不是为了通过 shellcheck 而写的，然后你反驳我说 shellcheck 给的建议都很值得参考，有必要解决。
这里我刚好联系上面的回复再澄清一下我的意思，我的意思是在你遵循 shellcheck 的建议对脚本做改进时，可以多考虑下 ROI。
我最开始参与到这个项目的贡献也是基于 shellcheck 对脚本写法的规范，所以在我看来你和我很像。但是我和你不同的地方在于，我不喜欢为了 shellcheck 给的一些标绿的低优先级 lint 建议大费周章，除非这样改过以后能让脚本的逻辑更清晰，日后维护更方便。

这就是为什么你最近这么多 PR 我都几乎没有提出反对意见，但只有上面你很说得出一番道理的改动我不接受的原因——你的 PR 确实让很多函数的逻辑更加清晰，但只要能确认修改后的脚本还是能像原来那样工作，就算花费我再多的时间做判断，这个 ROI 在我看来都是值得的。但一旦你的改动可能让用户困惑，这个 ROI 在我看来就不值得。

2020-09-18 05:39 UTC, DuckSoft commented on install-release.sh
> +    echo '  --specific       Install the specified version of V2Ray, e.g., --specific v4.18.0'
我觉得原有的写法比 @xiagw 的新写法更好。
另外，命令行参数最好不要随意改变，这是破坏性变更。

2020-09-18 05:44 UTC, xiagw commented
不讲那么多了。
不是那么重要，
你说希望解决参数问题，
我给个较好的示范而已。

2020-09-18 05:46 UTC, xiagw commented on install-release.sh
> +## Demo function for processing parameters
look here

2020-09-19 08:55 UTC, IceCodeNew commented on install-release.sh
> +    echo "usage: $0 [--remove | --specific number | -c | -f | -h | -l | -p]"
```suggestion
    echo "usage: $0 [--remove | --version number | -c | -f | -h | -l | -p]"
```

2020-09-19 08:55 UTC, IceCodeNew commented on install-release.sh
> +    echo '  [-p address] [--specific number | -c | -f]'
```suggestion
    echo '  [-p address] [--version number | -c | -f]'
```

2020-09-19 08:55 UTC, IceCodeNew commented on install-release.sh
> +    echo '  --specific       Install the specified version of V2Ray, e.g., --specific v4.18.0'
```suggestion
    echo '  --version       Install the specified version of V2Ray, e.g., --version v4.18.0'
```

2020-09-19 08:57 UTC, IceCodeNew commented on install-release.sh
> +## Demo function for processing parameters
> look here

不好意思，没明白你说这句话的用意。

2020-09-19 08:59 UTC, IceCodeNew commented on install-release.sh
> +        '--specific')
```suggestion
        '--version')
```

2020-09-19 09:03 UTC, IceCodeNew commented on install-release.sh
> +            break  ## 跳出while
这里的改写逻辑总的来说是正确的，但是我会考虑尽量保持和原来一致的行为。
比如当用户同时给了 `--remove` 参数和其他参数的时候，可以肯定这不是脚本应该继续执行下去的场景。
在别的地方这么写没有问题，但在这里我觉得还是应该尽量让脚本“更容易出错退出”，也比给用户不小心卸载 v2ray 的机会来的好。

2020-09-19 09:04 UTC, IceCodeNew commented on install-release.sh
> +            REMOVE='1'
```suggestion
            if [[ "$#" -gt '1' ]]; then
```

2020-09-19 09:05 UTC, IceCodeNew commented on install-release.sh
> +            break  ## 跳出while
```suggestion
              echo 'error: Please enter the correct parameters.'
```

2020-09-19 09:06 UTC, IceCodeNew commented on install-release.sh
> +            ;;
```suggestion
              exit 1
```

2020-09-19 09:22 UTC, IceCodeNew commented on install-release.sh
> +                break ##跳出while
```suggestion
                break
```

2020-09-19 09:23 UTC, IceCodeNew commented on install-release.sh
> +                break ##跳出while
```suggestion
                break
```

2020-09-19 09:23 UTC, IceCodeNew commented on install-release.sh
> +                break ##跳出while
```suggestion
                break
```

2020-09-19 09:25 UTC, IceCodeNew commented on install-release.sh
> -            '-h' | '--help')
如果你决心要删掉 `help` 参数，最好另起一个 PR。
修改缩进也是同样的道理。
不然 diff 很大，审核起来非常花精力又难受。

2020-09-19 09:28 UTC, IceCodeNew commented on install-release.sh
> +                break ##跳出while
```suggestion
                break
```

2020-09-19 09:31 UTC, IceCodeNew commented on install-release.sh
> +                if echo "${2:?undefine var}" | grep -qEo '^(http|https|socks4|socks4a|socks5|socks5h)://'; then
```suggestion
                if echo "${2:?undefine var}" | grep -qEo '^(https?|socks4a?|socks5h?):\/\/'; then
```

2020-09-19 09:32 UTC, IceCodeNew commented on install-release.sh
> +        shift ## 参数左移
```suggestion
        shift
```

2020-09-19 09:32 UTC, IceCodeNew commented on install-release.sh
> +                shift ## 参数左移
```suggestion
                shift
```

2020-09-19 09:33 UTC, IceCodeNew commented on install-release.sh
> +    # [[ "$HELP" -eq '1' ]] && show_help
```suggestion
    [[ "$HELP" -eq '1' ]] && show_help
```

2020-09-19 09:35 UTC, IceCodeNew commented on install-release.sh
> +                show_help
```suggestion
                echo "$0: unknown option -- -"
```

2020-09-19 09:36 UTC, IceCodeNew commented on install-release.sh
> +        echo "{}" >"${JSON_PATH}config.json"
```suggestion
        echo "{}" > "${JSON_PATH}/config.json"
```

2020-09-19 09:41 UTC, IceCodeNew approved these changes

2020-09-19 09:42 UTC, merged