Finishing off #67
v2fly/fhs-install-v2ray pull request #148
Opened 2020-09-28 02:51 UTC by DuckSoft

This closes #67. 
NOTE: Please squash.

2020-09-28 09:44 UTC, kslr approved these changes

2020-09-28 12:18 UTC, nicholascw approved these changes

2020-09-28 12:20 UTC, nicholascw requested changes
language alignment: use zh version link? 

https://zh.wikipedia.org/wiki/%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F%E5%B1%82%E6%AC%A1%E7%BB%93%E6%9E%84%E6%A0%87%E5%87%86

2020-09-29 02:33 UTC, DuckSoft commented
> language alignment: use zh version link?
> 
> https://zh.wikipedia.org/wiki/%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F%E5%B1%82%E6%AC%A1%E7%BB%93%E6%9E%84%E6%A0%87%E5%87%86

怕又有人搞事问为什么不选简中/新中/港中/台正，所以直接英文，自己选去

2020-09-29 02:53 UTC, IceCodeNew commented
草，绝了。

2020-09-29 03:12 UTC, merged

2020-09-29 04:40 UTC, IceCodeNew commented
@DuckSoft 说好的 squash 呢？