Update install-release.sh
v2fly/fhs-install-v2ray pull request #77
Opened 2020-09-02 12:04 UTC by DolorHunter

Add func enable v2ray

2020-09-02 12:51 UTC, IceCodeNew commented on install-release.sh
> +        enable_v2ray
我建议不要把 `enable_v2ray` 放在这里，而是放在 `'Please execute the command: systemctl enable v2ray; systemctl start v2ray'` 这句话之后。

2020-09-02 12:51 UTC, IceCodeNew requested changes
另外形式上可以是 echo 一个询问，然后 `read -rp` 读取用户输入，这样用户可以自己选择是否 enable v2ray。

2020-09-02 12:56 UTC, kirin10000 commented
> 另外形式上可以是 echo 一个询问，然后 `read -rp` 读取用户输入，这样用户可以自己选择是否 enable v2ray。

@IceCodeNew 不推荐，对第三方脚本作者(比如我)很不友好。可以加在脚本的启动选项里，比如 bash install-release.sh --enable-service

2020-09-02 13:28 UTC, IceCodeNew commented
> > 另外形式上可以是 echo 一个询问，然后 `read -rp` 读取用户输入，这样用户可以自己选择是否 enable v2ray。
> 
> @IceCodeNew 不推荐，对第三方脚本作者(比如我)很不友好。可以加在脚本的启动选项里，比如 bash install-release.sh --enable-service

上面只是推荐了一种形式而已，别的形式这些都可以再讨论，反正看作者自己最后愿意怎么实现了。
另外在编写第三方脚本的时候需要实现无用户介入的方式完成 `read -rp` 也是可以的，我不觉得这里有什么问题。

2020-09-02 13:45 UTC, kirin10000 commented
> > > 另外形式上可以是 echo 一个询问，然后 `read -rp` 读取用户输入，这样用户可以自己选择是否 enable v2ray。
> > 
> > 
> > @IceCodeNew 不推荐，对第三方脚本作者(比如我)很不友好。可以加在脚本的启动选项里，比如 bash install-release.sh --enable-service
> 
> 上面只是推荐了一种形式而已，别的形式这些都可以再讨论，反正看作者自己最后愿意怎么实现了。
> 另外在编写第三方脚本的时候需要实现无用户介入的方式完成 `read -rp` 也是可以的，我不觉得这里有什么问题。

好吧，我傻了

2020-09-02 17:16 UTC, IceCodeNew commented on install-release.sh
> +        enable_v2ray
用一种你觉得合适的方式，让这一项事务变成可选执行项。

2020-09-02 23:12 UTC, kslr commented
考虑没有默认配置的存在，我觉得另外启动更加合适，也可以让他们知道是由 systemd 处理，方便 debug

2020-09-03 01:00 UTC, closed without merging

2020-09-03 01:07 UTC, DolorHunter commented
如果没有默认配置的话, 确实没法直接把 start 和 enable 写进去脚本作为默认操作. 就算脚本做了 enable 选项, 第一次下载并手动写入配置后, 仍然需要手动 start. 因此, 把enable 写进脚本似乎意义不大.